# docker-compose.yml
version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: translation_mgr
